### ISSUE TITLE
7.50 incompatibility

### ISSUE THREAD

**Issue by jelliottp** [abap2UI5-addons/layout-variant-management#14]
As mentioned in the SE16 repo, there's a few syntax errors here for 7.50 incompatibility. I'd push a PR but I'm not exactly sure what the fix is here, particularly considering the use of `CORRESPONDING` complicating things.

Class `z2ui5_cl_pop_to_sel_w_layout`:
![Image](https://github.com/user-attachments/assets/ee0efff9-1485-4278-a2d7-6e54313fb1ca)

![Image](https://github.com/user-attachments/assets/f840fdc8-ae7b-4c4b-ba03-a90463824f3f)

**Comment by oblomov-dev** [comment]
fixed it now with:
```abap
        ASSIGN ms_result-row->* TO FIELD-SYMBOL(<any>).
        MOVE-CORRESPONDING <line> TO <any>.
```
and
```abap
    ASSIGN mr_tab->* TO FIELD-SYMBOL(<in>).
    ASSIGN mr_out->* TO FIELD-SYMBOL(<out>).
    MOVE-CORRESPONDING mr_tab->* TO <in>.
    z2ui5_cl_util=>itab_corresponding(
      EXPORTING
        val = <in>
      CHANGING
        tab = <out>
    ).
    "mr_out->* = CORRESPONDING #( mr_tab->* ).
```
you can give it a try again.

**Comment by jelliottp** [comment]
Unfortunately you still can't dereference a generic with MOVE-CORRESPONDING like this, and `mr_out_tmp->* = mr_out->*` is not allowed either.

![Image](https://github.com/user-attachments/assets/76d5d5d6-4a32-4fd6-854b-fa3437690646)

**Comment by oblomov-dev** [comment]
Ah just delete line 234, it’s not needed, forgot to delete.

**Comment by jelliottp** [comment]
Thanks, submitted one last one for line 254: https://github.com/abap2UI5-addons/layout-variant-management/pull/15

**Comment by jelliottp** [comment]
Looks good now!
